FROM mongo:latest

ENV MONGO_INITDB_ROOT_USERNAME ${MONGO_INITDB_ROOT_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD ${MONGO_INITDB_ROOT_PASSWORD}
ENV MONGO_INITDB_DATABASE ${MONGO_INITDB_DATABASE}

COPY ./data/json/ricknmorty.json /data/json/ricknmorty.json

ADD ./data/scripts/initdb.js /docker-entrypoint-initdb.d/

